<?php

namespace Ais\GedungBundle\Repository;

/**
 * GedungRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GedungRepository extends \Doctrine\ORM\EntityRepository
{
}
